version: '3.8'
services:
  app:
    image: openjdk:17-jdk-slim # Use the appropriate JDK version for your project
    container_name: portfolio-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1Vd@sawarkar
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: [ "java", "-jar", "portfolio-management-0.0.1-SNAPSHOT.jar" ]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1Vd@sawarkar
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
